# Generated by Django 5.0.6 on 2024-09-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0013_alter_socialuser_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="allowedDomains",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
