# Generated by Django 5.0.6 on 2024-09-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0014_instance_alloweddomains"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialuser",
            name="username",
            field=models.CharField(default={"all"}, max_length=100),
        ),
    ]
