# Generated by Django 5.0.6 on 2024-09-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0015_alter_socialuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="allowedDomains",
            field=models.JSONField(blank=True, default=["*"], null=True),
        ),
        migrations.AlterField(
            model_name="socialuser",
            name="username",
            field=models.CharField(default="", max_length=100),
        ),
    ]
