# Generated by Django 5.0.6 on 2024-09-12 20:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0016_alter_instance_alloweddomains_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instance",
            old_name="allowedDomains",
            new_name="allowed_domains",
        ),
    ]
