# Generated by Django 5.0.6 on 2024-09-12 21:11

import live.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0017_rename_alloweddomains_instance_allowed_domains"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="allowed_domains",
            field=models.JSONField(
                blank=True, default=live.models.default_allowed_domains, null=True
            ),
        ),
    ]
